#!/bin/bash
# chkconfig:   2345 90 10
# description:  memon_agent is the agent to monitor memory parts of the host


prog="/root/VirtualCluster/Matcher.py"
start()
{
  [ -x $porg ] || exit 1
  if [ -r /tmp/vm_match.pid ]
  then
  echo $prog " is already running"
  return 0
  fi

  echo "starting "$prog"..."
  $prog start
  RET=$?
  return $RET
}

stop()
{
  if [ -r /tmp/vm_match.pid ]
  then
    echo "stopping "$prog"..."
    $prog stop
    RET=$?
  else
    echo $prog " is already stopped!"
    RET=0
  fi
  return $RET
}

restart()
{
  if [ -r /tmp/vm_match.pid ]
    then
    echo "restarting "$prog"..."
    $prog restart
    RET=$?
  else
    echo $prog " is already stopped, starting it..."
    $prog start
    RET=$?
  fi
  return $RET
}
status()
{
  if [ -r /tmp/vm_match.pid ]
  then
    pid=`cat /tmp/vm_match.pid`
    ps -ef|grep $pid|grep -v grep >/dev/null
    rt=$?
    if [ $rt -eq 0 ]
    then
      echo  $prog "is running"
      return 0
    else
       echo $prog "is dead but /tmp/vm_match.pid exists!"
       return 1
    fi
  else
    if [ -r /tmp/vm_match.pid.lock ]
    then
      ps -ef|grep Matcher|grep -v grep >/dev/null
      rt=$?
      if [ $rt -ne 0 ];then
        echo $prog " is dead, but /tmp/vm_match.pid.lock still exsits!"
	return 2	
      fi
     else
	ps -ef|grep Matcher|grep -v grep >/dev/null
        rt=$?
        if [ $rt -ne 0 ];then
          echo $prog " is stopped"
          return 3
	fi
     fi
  fi
}
case "$1" in 
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
        status)
		status
		;;
	*)
		echo "usage: $0 start|stop|restart|status"
		RET=2
esac

exit $RET
		
